"""Main TUI application class for Legal Extractor."""

import os
import sys
from pathlib import Path
from typing import ClassVar

# Add tui_safety to Python path if available
_tui_safety_path = os.path.expanduser("~/.local/lib/python")
if os.path.exists(_tui_safety_path) and _tui_safety_path not in sys.path:
    sys.path.insert(0, _tui_safety_path)

from textual.app import App
from textual.binding import Binding
from textual.screen import Screen

from legal_extractor_tui.config import APP_NAME, APP_VERSION, STYLES_DIR
from legal_extractor_tui.screens import HelpScreen, MainScreen
from legal_extractor_tui.themes import (
    VIBE_NEON_THEME,
    VIBE_MATRIX_THEME,
    VIBE_SYNTHWAVE_THEME,
    MINIMAL_DARK_THEME,
)

# Try to import and install tui_safety for mouse tracking protection
try:
    import tui_safety
    tui_safety.install()
except ImportError:
    # tui_safety not available - continue without mouse tracking protection
    pass


class LegalExtractorApp(App):
    """TUI application for Brazilian legal document text extraction.

    This application provides a terminal user interface for extracting and
    cleaning text from PDF files generated by Brazilian judicial systems.

    Features:
        - File selection and browsing
        - Automatic judicial system detection
        - Real-time extraction progress
        - Text preview and metadata display
        - Multiple export formats (TXT, MD, JSON)
        - Theme customization

    Attributes:
        theme_name: Name of the active theme
        dev_mode: Enable development/debug features
        initial_file: Optional file to load on startup
    """

    TITLE = APP_NAME
    SUB_TITLE = f"v{APP_VERSION} - Extração de Documentos Jurídicos"

    CSS_PATH: ClassVar[list[Path | str]] = [
        STYLES_DIR / "animations.tcss",
        STYLES_DIR / "base.tcss",
        STYLES_DIR / "layout.tcss",
        STYLES_DIR / "widgets.tcss",
    ]

    BINDINGS: ClassVar[list[Binding]] = [
        Binding("q", "quit", "Sair"),
        Binding("?", "show_help", "Ajuda"),
        Binding("ctrl+r", "run_extraction", "Extrair", show=True),
        Binding("escape", "cancel_extraction", "Cancelar"),
        Binding("ctrl+o", "open_file", "Abrir PDF"),
        Binding("ctrl+s", "save_result", "Salvar"),
        Binding("ctrl+p", "command_palette", "Comandos", show=False),
    ]

    SCREENS: ClassVar[dict[str, type[Screen]]] = {
        "main": MainScreen,
        "help": HelpScreen,
    }

    def __init__(
        self,
        theme_name: str = "vibe-neon",
        dev_mode: bool = False,
        initial_file: str | Path | None = None,
    ) -> None:
        """Initialize the Legal Extractor application.

        Args:
            theme_name: Name of the theme to use (default: vibe-neon)
            dev_mode: Enable development mode with debug features
            initial_file: Optional PDF file to load on startup
        """
        super().__init__()
        self._theme_name = theme_name
        self._dev_mode = dev_mode
        self._initial_file = Path(initial_file) if initial_file else None

        # Register all available themes
        self.register_theme(VIBE_NEON_THEME)
        self.register_theme(VIBE_MATRIX_THEME)
        self.register_theme(VIBE_SYNTHWAVE_THEME)
        self.register_theme(MINIMAL_DARK_THEME)

    def on_mount(self) -> None:
        """Called when the app is mounted.

        Sets up the theme and screen, and optionally loads
        the initial file if provided.
        """
        # Apply theme and dark mode
        self.theme = self._theme_name
        self.dark = True

        # Push main screen
        main_screen = MainScreen(initial_file=self._initial_file)
        self.push_screen(main_screen)

    def action_show_help(self) -> None:
        """Display the help screen with keybindings and documentation."""
        self.push_screen(HelpScreen())

    def action_run_extraction(self) -> None:
        """Start PDF extraction process.

        Delegates to the current screen's action_run_extraction if available.
        """
        current_screen = self.screen
        if hasattr(current_screen, "action_run_extraction"):
            current_screen.action_run_extraction()  # type: ignore

    def action_cancel_extraction(self) -> None:
        """Cancel ongoing extraction operation.

        Delegates to the current screen's action_cancel_extraction if available.
        """
        current_screen = self.screen
        if hasattr(current_screen, "action_cancel_extraction"):
            current_screen.action_cancel_extraction()  # type: ignore

    def action_open_file(self) -> None:
        """Open file selection dialog.

        Delegates to the current screen's action_open_file if available.
        """
        current_screen = self.screen
        if hasattr(current_screen, "action_open_file"):
            current_screen.action_open_file()  # type: ignore

    def action_save_result(self) -> None:
        """Export extraction results.

        Delegates to the current screen's action_save_result if available.
        """
        current_screen = self.screen
        if hasattr(current_screen, "action_save_result"):
            current_screen.action_save_result()  # type: ignore
